eureka:
   client:
      service-url: 
         defualtZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: HealthInsurance-AdminModule
        uri: lb://HealthInsurance-AdminModule
        predicates:
        - Path=/admin/**

      - id: HealthInsurance-Application-Registration
        uri: lb://HealthInsurance-Application-Registration
        predicates:
        - Path=/citizen/**

      - id: HealthInsurance-Benfit-Issuance
        uri: lb://HealthInsurance-Benfit-Issuance
        predicates:
        - Path=/benfit/**

      - id: HealthInsurance-Correspondence
        uri: lb://HealthInsurance-Correspondence
        predicates:
        - Path=/correspondence/**

      - id: HealthInsurance-Data-Collection
        uri: lb://HealthInsurance-Data-Collection
        predicates:
        - Path=/data/**

      - id: HealthInsurance-Eligibility-Determination
        uri: lb://HealthInsurance-Eligibility-Determination
        predicates:
        - Path=/eligibility/**

      - id: HealthInsurance-Reports-API
        uri: lb://HealthInsurance-Reports-API
        predicates:
        - Path=/reports/**

      - id: HealthInsurance-SSA
        uri: lb://HealthInsurance-SSA
        predicates:
        - Path=/ssa-web-api/**

      - id: HealthInsurance-User-Management
        uri: lb://HealthInsurance-User-Management
        predicates:
        - Path=/user/**
  application:
    name: HealthInsuranceSystem-API-Gateway

server:
  port: 7171