spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: oracle
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: java17
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 4040