#Configure Properties from Config Server
spring:
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: default
  application:
    name: HealthInsurance-Eligibility_Determination
server:
  port: 4040