#Configure Properties from Config Server
spring:
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: default
  application:
    name: HealthInsurance-AdminModule

plans-api:
  messages:
    planregsucc: Plans Registered Successfully
    planregfail: Plans Registered Failed
    planupdatesucc: Plan Details Updated Successfully
    planupdatefail: Plan Details Not Updated
    plandeletesucc: Plan Deleted Successfully
    plandeletefail: Plan Not Deleted
server:
  port: 4646