spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: oracle
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: java17
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

plans-api:
  messages:
    planregsucc: Plans Registered Successfully
    planregfail: Plans Registered Failed
    planupdatesucc: Plan Details Updated Successfully
    planupdatefail: Plan Details Not Updated
    plandeletesucc: Plan Deleted Successfully
    plandeletefail: Plan Not Deleted
  