#Configure Properties from Config Server
spring:
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: default
  application:
    name: HealthInsurance-Reports_API
#server port
server:
  port: 3333

