spring:
  application:
    name: HealthInsuranceSystem-ConfiServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madhukrishnaonline/Config-Server-YML.git
          clone-on-start: true
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
server:
  port: 9999